# --- Site basics ---
lang: ko-KR
timezone: Asia/Seoul

title: 컴고 박태환 공부 기록
tagline: 정성과 열정을 담은 나의 기록
description: >-
  A minimal, responsive and feature-rich Jekyll theme for technical writing.
url: "https://taehwan0809.github.io"
baseurl: ""   # user.github.io는 빈 문자열

author:
  name: Taehwan Park
  email: dcpop28201004@gmail.com

social:
  links:
    - https://github.com/taehwan0809

# --- Theme (Flexton) ---
plugins:
  - jekyll-remote-theme
  - jekyll-paginate       # 목록 페이지 나눔 사용
  - jekyll-sitemap        # 선택: 사이트맵
  - jekyll-feed           # 선택: RSS/Atom 피드
remote_theme: artemsheludko/flexton

# --- Pagination ---
paginate: 10
paginate_path: "/page:num/"

# --- Appearance / content ---
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

# --- Optional analytics / comments (원하면 값만 채우면 됨) ---
google_analytics:    # ex) G-XXXXXXX
disqus:              # ex) your-disqus-shortname

# --- Build ---
exclude:
  - README.md
  - LICENSE
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - docs
  - tools
  - rollup.config.js
  - purgecss.js
  - eslint.config.js
  - stylelint.config.json
  - package.json